

name: Code-Analisys


on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    
  workflow_dispatch:

jobs:   
  sast:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p .
  dast:
    permissions:
      packages: write
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - name: DAST
        run: |
          return 0
  scout:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: SCOUT
        run:  |
          ls -la
          if [ -f "$PWD/Dockerfile" ]; then \
            docker build -t analyzed-app . && \
            docker scout cves analysed-app -o scout-cves.txt && \
            docker scout recommendations analysed-app -o scout-recommendations.txt \ 
          else \
            echo "Dockerfile nao encontrada" \ 
          fi

              
    
