

name: Code-Analisys


on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    
  workflow_dispatch:

jobs:   
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p . >> sast.txt
      - uses: actions/upload-artifact@v4
        with:
          path:  sast.txt
        
        
  dast:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - name: DAST
        run: |
          return 0
      - uses: actions/upload-artifact@v4
        with:
          path:  dast.txt
  scout:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: SCOUT
        run:  |
          if [ -f "$PWD/Dockerfile" ]; then \
            docker build -t analyzed-app . && \
            docker images && \
            docker scout cves analyzed-app -o scout-cves.txt && \
            docker scout recommendations analyzed-app -o scout-recommendations.txt \ 
          else \
            echo "Dockerfile nao encontrada" \ 
          fi
      - uses: actions/upload-artifact@v4
        with:
          path: |
            scout-cves.txt
            scout-recommendations.txt

              
    
