

name: Code-Analisys


on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    
  workflow_dispatch:

jobs:   
  sast:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest-beta
          horusec start -p .
  dast:
    permissions:
      packages: write
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - name: DAST
        run: |
          return 0
  scout:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SCOUT
        run: |
          grep "Dockerfile" . 
              
    
